baseURL: "https://grownops.github.io/"
languageCode: "en-us"
title: "GrownOps Community"
featured_image: ''
omit_header_text: true

module:
  imports:
    - path: github.com/theNewDynamic/gohugo-theme-ananke

DefaultContentLanguage: en
SectionPagesMenu: ''
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: '/images/favicon.ico'
  site_logo: '/images/tra_grownops_logo-color-circle-copy.png'
  description: join technical operations leaders focused on excellence and growth
  facebook: ''
  twitter: ''
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: 'slack://grownopsio.slack.com'
  stackoverflow: ''
  rss: ''
  background_color_class: bg-grey
  recent_posts_number: 0
